// <auto-generated />
using System;
using DemonBack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DemonBack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226163822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DemonBack.Core.Entities.AnimePath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("character_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("anime_paths", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnimeIconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("anime_icon_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.PathExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("PathId")
                        .HasColumnType("uuid")
                        .HasColumnName("path_id");

                    b.Property<int?>("RecommendedReps")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_reps");

                    b.Property<int?>("RecommendedSets")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_sets");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PathId", "DayOfWeek", "OrderIndex");

                    b.ToTable("path_exercises", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("integer")
                        .HasColumnName("current_exp");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_level");

                    b.Property<decimal?>("CurrentWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("current_weight_kg");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Goal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PreferredUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_unit");

                    b.Property<string>("RankTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank_title");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer")
                        .HasColumnName("streak_days");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserBodyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ArmSize")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("arm_size");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("body_fat_percent");

                    b.Property<decimal?>("ChestSize")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("chest_size");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("logged_at");

                    b.Property<decimal?>("MuscleMassKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("muscle_mass_kg");

                    b.Property<string>("PhotoBackUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_back_url");

                    b.Property<string>("PhotoFrontUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_front_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WaistSize")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("waist_size");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("body_logs", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SourcePathId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_path_id");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourcePathId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("user_plans", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<TimeOnly>("NotifyTime")
                        .HasColumnType("time")
                        .HasColumnName("notify_time");

                    b.Property<Guid>("UserPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("UserPlanId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("user_plan_days", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlanDayExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("integer")
                        .HasColumnName("target_reps");

                    b.Property<decimal?>("TargetRpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("target_rpe");

                    b.Property<int?>("TargetSets")
                        .HasColumnType("integer")
                        .HasColumnName("target_sets");

                    b.Property<Guid>("UserPlanDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_plan_day_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserPlanDayId", "OrderIndex");

                    b.ToTable("user_plan_day_exercises", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_schedule_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time")
                        .HasColumnName("scheduled_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuggestionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suggestion_reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserPlanDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_plan_day_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentScheduleId");

                    b.HasIndex("UserPlanDayId");

                    b.HasIndex("UserId", "ScheduledDate");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("workout_schedules", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<short?>("FatigueScore")
                        .HasColumnType("smallint")
                        .HasColumnName("fatigue_score");

                    b.Property<short?>("MoodScore")
                        .HasColumnType("smallint")
                        .HasColumnName("mood_score");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<decimal?>("SessionRpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("session_rpe");

                    b.Property<decimal?>("SleepHours")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("sleep_hours");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId", "OrderIndex");

                    b.ToTable("workout_session_exercises", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPr")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pr");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warmup");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rpe");

                    b.Property<Guid>("SessionExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_exercise_id");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("SessionExerciseId", "SetNumber");

                    b.ToTable("workout_sets", (string)null);
                });

            modelBuilder.Entity("DemonBack.Core.Entities.PathExercise", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.Exercise", "Exercise")
                        .WithMany("PathExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemonBack.Core.Entities.AnimePath", "Path")
                        .WithMany("Exercises")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserBodyLog", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.User", "User")
                        .WithMany("BodyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlan", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.AnimePath", "SourcePath")
                        .WithMany("DerivedUserPlans")
                        .HasForeignKey("SourcePathId");

                    b.HasOne("DemonBack.Core.Entities.User", "User")
                        .WithMany("Plans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePath");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlanDay", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.UserPlan", "UserPlan")
                        .WithMany("Days")
                        .HasForeignKey("UserPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPlan");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlanDayExercise", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.Exercise", "Exercise")
                        .WithMany("UserPlanDayExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemonBack.Core.Entities.UserPlanDay", "UserPlanDay")
                        .WithMany("Exercises")
                        .HasForeignKey("UserPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("UserPlanDay");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSchedule", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.WorkoutSchedule", "ParentSchedule")
                        .WithMany("Reschedules")
                        .HasForeignKey("ParentScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DemonBack.Core.Entities.User", "User")
                        .WithMany("WorkoutSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemonBack.Core.Entities.UserPlanDay", "UserPlanDay")
                        .WithMany("WorkoutSchedules")
                        .HasForeignKey("UserPlanDayId");

                    b.Navigation("ParentSchedule");

                    b.Navigation("User");

                    b.Navigation("UserPlanDay");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSession", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.WorkoutSchedule", "Schedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("DemonBack.Core.Entities.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSessionExercise", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.Exercise", "Exercise")
                        .WithMany("WorkoutSessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemonBack.Core.Entities.WorkoutSession", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSet", b =>
                {
                    b.HasOne("DemonBack.Core.Entities.WorkoutSessionExercise", "SessionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("SessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.AnimePath", b =>
                {
                    b.Navigation("DerivedUserPlans");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.Exercise", b =>
                {
                    b.Navigation("PathExercises");

                    b.Navigation("UserPlanDayExercises");

                    b.Navigation("WorkoutSessionExercises");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.User", b =>
                {
                    b.Navigation("BodyLogs");

                    b.Navigation("Plans");

                    b.Navigation("WorkoutSchedules");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.UserPlanDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSchedules");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSchedule", b =>
                {
                    b.Navigation("Reschedules");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("DemonBack.Core.Entities.WorkoutSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
